easy_admin:
    design:
        menu:
            - {label: "Entidades", permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']}
            - label: "Clasificacion"
              icon: "list-ol"
              permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
              children:
                  - {entity: Clasificacion, label: "Lista clasificacion", icon: "th-list"}
                  - {entity: Clasificacion, label: "Añadir clasificacion", icon: "plus", params: {action: 'new'}}
            - label: "Equipo"
              icon: "shield-alt"
              permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
              children:
                      - {entity: Equipo, label: "Lista equipos", icon: "th-list"}
                      - {entity: Equipo, label: "Añadir equipo", icon: "plus", params: {action: 'new'}}
            - label: "Estadio"
              icon: "building"
              permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
              children:
                      - {entity: Estadio, label: "Lista estadios", icon: "th-list"}
                      - {entity: Estadio, label: "Añadir estadio", icon: "plus", params: {action: 'new'}}
            - label: "Jornada"
              permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
              children:
                      - {entity: Jornada, label: "Lista jornadas", icon: "th-list"}
                      - {entity: Jornada, label: "Añadir jornada", icon: "plus", params: {action: 'new'}}
            - label: "Jugador"
              icon: "running"
              permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
              children:
                      - {entity: Jugador, label: "Lista jugadores", icon: "th-list"}
                      - {entity: Jugador, label: "Añadir jugador", icon: "plus", params: {action: 'new'}}
            - label: "Liga"
              icon: "trophy"
              permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
              children:
                      - {entity: Liga, label: "Lista ligas", icon: "th-list"}
                      - {entity: Liga, label: "Añadir liga", icon: "plus", params: {action: 'new'}}
            - label: "Noticia"
              icon: "newspaper"
              permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
              children:
                      - {entity: Noticia, label: "Lista noticias", icon: "th-list"}
                      - {entity: Noticia, label: "Añadir noticia", icon: "plus", params: {action: 'new'}}
            - label: "Partido"
              icon: "poll"
              permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
              children:
                      - {entity: Partido, label: "Lista partidos", icon: "th-list"}
                      - {entity: Partido, label: "Añadir partido", icon: "plus", params: {action: 'new'}}
            - label: "Posicion"
              icon: "map-pin"
              permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
              children:
                      - {entity: Posicion, label: "Lista posiciones", icon: "th-list"}
                      - {entity: Posicion, label: "Añadir posicion", icon: "plus", params: {action: 'new'}}
            - label: "Usuario"
              permission: 'ROLE_ADMIN'
              icon: "user"
              children:
                      - {entity: Usuario, label: "Lista usuarios", icon: "th-list", permission: 'ROLE_ADMIN'}
                      - {entity: Usuario, label: "Añadir usuario", icon: "plus", params: {action: 'new'}, permission: 'ROLE_ADMIN'}
            - { label: 'Otros' }
            - { label: 'Página', url: '../', icon: 'home', target: '_blank' }

    site-name: 'Futbolistics'
    entities:
        # List the entity class name you want to manage
      Clasificacion:
          class: App\Entity\Clasificacion
          list:
            item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
          edit:
            item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
          delete:
            item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
          new:
            item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
      Equipo:
        class: App\Entity\Equipo
        image_base_path: 'assets/images/escudos/'
        form:
          fields:
            - nombre
            - entrenador
            - trofeos
            - region
            - fundacion
            - estadio
            - liga
            - { property: 'fotoPerfilFile', type: 'vich_image', label: 'Foto escudo' }
        list:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
          fields:
            - { property: 'id', type: 'integer' }
            - { property: 'nombre', type: 'string' }
            - { property: 'entrenador', type: 'string' }
            - { property: 'trofeos', type: 'integer'}
            - { property: 'region', type: 'string' }
            - { property: 'fundacion', type: 'integer' }
            - { property: 'fotoperfil', type: 'image' }
            - { property: 'estadio'}
            - { property: 'liga'}
        edit:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
        delete:
            item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
        new:
            item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
      Estadio:
        class: App\Entity\Estadio
        image_base_path: 'assets/images/estadios/'
        form:
          fields:
            - nombre
            - ciudad
            - { property: 'fotoEstadioFile', type: 'vich_image', label: 'Foto estadio' }
        list:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
          fields:
            - { property: 'nombre', type: 'string' }
            - { property: 'ciudad', type: 'string' }
            - { property: 'fotoEstadio', type: 'image' }
        edit:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
        delete:
            item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
        new:
            item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
      Jornada:
        class: App\Entity\Jornada
        list:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
        edit:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
        delete:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
        new:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
      Jugador:
        class: App\Entity\Jugador
        list:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
        edit:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
        delete:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
        new:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
      Liga:
        class: App\Entity\Liga
        list:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
        edit:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
        delete:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
        new:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
      Noticia:
        class: App\Entity\Noticia
        image_base_path: 'assets/images/noticias/'
        form:
          fields:
            - titular
            - equipo
            - cuerpo
            - fecha
            - colaborador
            - { property: 'imagenFile', type: 'vich_image', label: 'Foto noticia' }
        list:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
          fields:
            - { property: 'titular', type: 'string' }
            - { property: 'equipo'}
            - { property: 'cuerpo'}
            - { property: 'fecha'}
            - { property: 'colaborador'}
            - { property: 'imagen', type: 'image' }
        edit:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
        delete:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
        new:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
      Partido:
        class: App\Entity\Partido
        list:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
        edit:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
        delete:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
        new:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
      Posicion:
        class: App\Entity\Posicion
        list:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
        edit:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
        delete:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
        new:
          item_permission: ['ROLE_ADMIN', 'ROLE_COLABORATOR']
      Usuario:
        class: App\Entity\Usuario
        image_base_path: 'assets/images/usuarios/'
        form:
          fields:
            - nombre
            - nombreCompleto
            - email
            - password
            - equipoFavorito
            - { property: 'rol', type: 'choice', type_options: { choices:  { 'ROLE_ADMIN': "ROLE_ADMIN", 'ROLE_COLABORATOR': "ROLE_COLABORATOR", 'ROLE_USER': "ROLE_USER"} } }
            - { property: 'fotoPerfilFile', type: 'vich_image', label: 'Foto usuario' }
        list:
          item_permission: 'ROLE_ADMIN'
          fields:
            - { property: 'nombre', type: 'string' }
            - { property: 'nombreCompleto', type: 'string' }
            - { property: 'nombreCompleto', type: 'email' }
            - { property: 'equipoFavorito'}
            - { property: 'rol'}
            - { property: 'fotoPerfil', type: 'image' }
        edit:
          item_permission: 'ROLE_ADMIN'
        delete:
          item_permission: 'ROLE_ADMIN'
        new:
          item_permission: 'ROLE_ADMIN'
