easy_admin:
    design:
        menu:
            - {label: "Entidades"}
            - label: "Clasificacion"
              children:
                  - {entity: Clasificacion, label: "Lista clasificacion", icon: "th-list"}
            - label: "Equipo"
              children:
                      - {entity: Equipo, label: "Lista equipos", icon: "th-list"}
                      - {entity: Equipo, label: "Añadir equipo", icon: "plus", params: {action: 'new'}}
            - label: "Estadio"
              children:
                      - {entity: Estadio, label: "Lista estadios", icon: "th-list"}
                      - {entity: Estadio, label: "Añadir estadio", icon: "plus", params: {action: 'new'}}
            - label: "Jornada"
              children:
                      - {entity: Jornada, label: "Lista jornadas", icon: "th-list"}
                      - {entity: Jornada, label: "Añadir jornada", icon: "plus", params: {action: 'new'}}
            - label: "Jugador"
              children:
                      - {entity: Jugador, label: "Lista jugadores", icon: "th-list"}
                      - {entity: Jugador, label: "Añadir jugador", icon: "plus", params: {action: 'new'}}
            - label: "Liga"
              children:
                      - {entity: Liga, label: "Lista ligas", icon: "th-list"}
                      - {entity: Liga, label: "Añadir liga", icon: "plus", params: {action: 'new'}}
            - label: "Noticia"
              children:
                      - {entity: Noticia, label: "Lista noticias", icon: "th-list"}
                      - {entity: Noticia, label: "Añadir noticia", icon: "plus", params: {action: 'new'}}
            - label: "Partido"
              children:
                      - {entity: Partido, label: "Lista partidos", icon: "th-list"}
                      - {entity: Partido, label: "Añadir partido", icon: "plus", params: {action: 'new'}}
            - label: "Posicion"
              children:
                      - {entity: Posicion, label: "Lista posiciones", icon: "th-list"}
                      - {entity: Posicion, label: "Añadir posicion", icon: "plus", params: {action: 'new'}}
            - label: "Rol"
              children:
                      - {entity: Rol, label: "Lista roles", icon: "th-list"}
                      - {entity: Rol, label: "Añadir rol", icon: "plus", params: {action: 'new'}}
            - label: "Usuario"
              children:
                      - {entity: Usuario, label: "Lista usuarios", icon: "th-list"}
                      - {entity: Usuario, label: "Añadir usuario", icon: "plus", params: {action: 'new'}}
    site-name: 'Futbolistics'
    entities:
        # List the entity class name you want to manage
      Clasificacion:
          class: App\Entity\Clasificacion
      Equipo:
        class: App\Entity\Equipo
        image_base_path: 'assets/images/escudos/'
        list:
          fields:
            - { property: 'id', type: 'integer' }
            - { property: 'nombre', type: 'string' }
            - { property: 'entrenador', type: 'string' }
            - { property: 'trofeos', type: 'integer' }
            - { property: 'region', type: 'string' }
            - { property: 'fundacion', type: 'integer' }
            - { property: 'fotoperfil', type: 'image' }
            - { property: 'estadio'}
            - { property: 'liga'}
      Estadio:
        class: App\Entity\Estadio
      Jornada:
        class: App\Entity\Jornada
      Jugador:
        class: App\Entity\Jugador
      Liga:
        class: App\Entity\Liga
      Noticia:
        class: App\Entity\Noticia
      Partido:
        class: App\Entity\Partido
      Posicion:
        class: App\Entity\Posicion
      Rol:
        class: App\Entity\Rol
      Usuario:
        class: App\Entity\Usuario
