vich_uploader:
    db_driver: orm

    mappings:
        equipo_images:
            uri_prefix: '%uploadsEquipo_path%'
            upload_destination: '%kernel.project_dir%/public/%uploadsEquipo_path%'
        estadio_images:
            uri_prefix: '%uploadsEstadio_path%'
            upload_destination: '%kernel.project_dir%/public/%uploadsEstadio_path%'
        usuario_images:
            uri_prefix: '%uploadsUsuario_path%'
            upload_destination: '%kernel.project_dir%/public/%uploadsUsuario_path%'
        noticia_images:
            uri_prefix: '%uploadsNoticia_path%'
            upload_destination: '%kernel.project_dir%/public/%uploadsNoticia_path%'